default_stages: [commit]
repos:
  - repo: https://github.com/yyang-pplus/config-sh.git
    rev: 1ac50d1aa0923c709f57161a5a19116dd0a31a59
    hooks:
      - id: shfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        stages: [commit]

  - repo: https://github.com/markdownlint/markdownlint.git
    rev: v0.11.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
