default_stages: [pre-commit]
repos:
  - repo: https://github.com/yyang-pplus/config-sh.git
    rev: b768af69778668afc67b14b11ec88f6c9ca0eb00
    hooks:
      - id: shfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [pre-commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        stages: [pre-commit]

  - repo: https://github.com/markdownlint/markdownlint.git
    rev: v0.13.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
