- id: astyle-c
  name: astyle-c
  description: Run astyle for C files.
  language: system
  entry: astyle
  types: [c]
  additional_dependencies: [astyle]

- id: astyle-cpp
  name: astyle-c++
  description: Run astyle for C++ files.
  language: system
  entry: astyle
  types: [c++]
  additional_dependencies: [astyle]

- id: astyle-cs
  name: astyle-c#
  description: Run astyle for C# files.
  language: system
  entry: astyle
  types: [c#]
  additional_dependencies: [astyle]

- id: shfmt
  name: shfmt
  description: Run shfmt for shell scripts.
  language: system
  entry: shfmt
  args: [-w]
  types: [shell]
  additional_dependencies: [shfmt]
