default_stages: [commit]
repos:
  - repo: https://github.com/yyang-pplus/config-sh.git
    rev: d4c1eee67d5941afd748118872cb19b89061b92a
    hooks:
      - id: shfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
        stages: [commit]
