default_stages: [commit]
repos:
  - repo: https://github.com/yyang-even/yyLinuxScripts
    rev: 30afb89b2b641664719d31a3d08cc298c40da292
    hooks:
      - id: shfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
        stages: [commit]
