default_stages: [commit]
repos:
  - repo: https://github.com/yyang-pplus/config-sh.git
    rev: 0c719cfc52fb3ef589e4387a26afd2f3b2bee1fc
    hooks:
      - id: shfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
        stages: [commit]

  - repo: https://github.com/markdownlint/markdownlint.git
    rev: v0.11.0
    hooks:
      - id: markdownlint
